services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "9095:9095"
      - "9095:9095/udp"
    networks:
      - app-network
    environment:
      - URL_HOST=localhost
      - URL_PORT=9095
      - WEB_MODE=${WEBMODE}

  service1:
    build:
      context: ./service
    ports:
      - "9096:9096"
      - "9096:9096/udp"
    networks:
      - app-network
    environment:
      - URL_HOST=localhost
      - URL_PORT=9096
      - WEB_MODE=${WEBMODE}
    depends_on:
      - gateway

  service2:
    build:
      context: ./service
    ports:
      - "9097:9097"
      - "9097:9097/udp"
    networks:
      - app-network
    environment:
      - URL_HOST=localhost
      - URL_PORT=9097
      - WEB_MODE=${WEBMODE}
    depends_on:
      - gateway

networks:
  app-network:
    driver: bridge