# version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "9095:9095"  #TCP
      - "9095:9095/udp"
    networks:
      - app-network
    environment:
      - URL_HOST=https://localhost
      - URL_PORT=9095
      - WEB_MODE=${WEBMODE} # HTML UDP TCP

  service1:
    build:
      context: ./service
    ports:
      - "9096:9096"
      - "9096:9096/udp"
    networks:
      - app-network
    environment:
      - URL_HOST=https://localhost
      - URL_PORT=9096
      - WEB_MODE=${WEBMODE} # HTTP UDP TCP


  # follower2:
  #   build:
  #     context: ./service
  #   networks:
  #     - app-network
  #   environment:
  #     - SERVER_ROLE=follower
  #     - SERVER_PORT=8083
  #     - LEADER_HOST=leader
  #     - FOLLOWER_ID=2
  #   depends_on:
  #     - leader

  # follower3:
  #   build:
  #     context: ./service
  #   networks:
  #     - app-network
  #   environment:
  #     - SERVER_ROLE=follower
  #     - SERVER_PORT=8084
  #     - LEADER_HOST=leader
  #     - FOLLOWER_ID=3
  #   depends_on:
  #     - leader

  # follower4:
  #   build:
  #     context: ./service
  #   networks:
  #     - app-network
  #   environment:
  #     - SERVER_ROLE=follower
  #     - SERVER_PORT=8085
  #     - LEADER_HOST=leader
  #     - FOLLOWER_ID=4
  #   depends_on:
  #     - leader

networks:
  app-network:
    driver: bridge